[package]
name = "fold-motion"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = []
ui = ["dep:fold-ui"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
fold-foundation.workspace = true
fold-project.workspace = true
fold-media.workspace = true
fold-render.workspace = true
fold-platform.workspace = true
fold-ui = { workspace = true, optional = true }
rustybuzz = "0.20"
unicode-bidi = "0.3"

[lints]
workspace = true
