[package]
name = "fold-app"
version.workspace = true
edition.workspace = true
publish.workspace = true
default-run = "fold-cli"

[features]
default = []
native-probe = ["desktop", "fold-ui/native-probe"]
desktop = ["dep:rfd", "dep:fold-ui", "dep:cpal", "dep:rtrb", "fold-timeline/ui", "fold-compositor/ui", "fold-motion/ui"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
fold-foundation.workspace = true
tempfile.workspace = true
fold-project.workspace = true
fold-media.workspace = true
fold-render.workspace = true
fold-platform.workspace = true
fold-timeline.workspace = true
fold-compositor.workspace = true
fold-motion.workspace = true
fold-ui = { workspace = true, optional = true }
cpal = { version = "0.15.3", optional = true }
rtrb = { version = "0.3", optional = true }
rfd = { version = "0.15", optional = true, default-features = false, features = ["xdg-portal", "async-std"] }

[[bin]]
name = "fold-cli"
path = "src/bin/cli.rs"

[[bin]]
name = "fold-desktop"
path = "src/bin/desktop.rs"
required-features = ["desktop"]

[lints]
workspace = true
